variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - teste
  - docker
  - build
  - deploy

cache:
  paths:
    - .m2/repository
    - target

teste:
  image: maven:latest
  stage: teste
  script:
    - mvn test

docker:
  stage: docker
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker-compose build
    - docker-compose up -d

build_job:
  image: maven:latest
  stage: build
  script:
    - mvn clean install -B

Deploy_job:
  stage: deploy
  script:
    - echo "Maven deploy started"

