version: '3.7'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: my-db
    restart: always
    environment:
      - MYSQL_DATABASE=filmes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
  keycloak:
    image: 'quay.io/keycloak/keycloak:25.0.2'
    container_name: my-keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8085
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - 'start-dev'
    ports:
      - 8085:8085

