version: '3.7'
services:
  mysql:
    image: 'mysql:8.0'
    container_name: my-db
    restart: always
    environment:
      - MYSQL_DATABASE=filmes
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
  keycloak:
    image: 'quay.io/keycloak/keycloak:25.0.2'
    container_name: my-keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_PORT: 8085
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command:
      ['start-dev', '--http-port=8085']
    ports:
      - 8085:8085

